#!/bin/bash
# ──────────────────────────────────────────────────────────────────────
# setup.sh — One-command bootstrap for ConvergeAI
# ──────────────────────────────────────────────────────────────────────
# Idempotent: safe to run multiple times. Skips steps already completed.
#
# What it does:
#   1. Checks for Goose CLI (installs via Homebrew if missing)
#   2. Creates a Python virtual environment and installs dependencies
#   3. Securely prompts for API keys (hidden input)
#   4. Writes secrets to .env (project root)
# ──────────────────────────────────────────────────────────────────────
set -e

# Resolve the directory this script lives in (works even if invoked from elsewhere)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo ""
echo "==================================="
echo "  ConvergeAI Setup"
echo "==================================="
echo ""

# ─── 1. Check for Goose CLI ──────────────────────────────────────────
if ! command -v goose &> /dev/null; then
    echo "[1/4] Goose CLI not found. Installing..."
    if command -v brew &> /dev/null; then
        brew install block/tap/goose
        echo "  -> Goose installed successfully."
    else
        echo "  ERROR: Homebrew not found."
        echo "  Please install Goose manually: https://block.github.io/goose/docs/getting-started/installation"
        exit 1
    fi
else
    echo "[1/4] Goose CLI found."
fi

# ─── 2. Python Virtual Environment ───────────────────────────────────
if [ ! -d ".venv" ]; then
    echo "[2/4] Building Python virtual environment..."

    # Check for python3
    if ! command -v python3 &> /dev/null; then
        echo "  ERROR: python3 not found. Please install Python 3.10+."
        exit 1
    fi

    python3 -m venv .venv
    .venv/bin/pip install --upgrade pip --quiet
    .venv/bin/pip install -r mcp/context_distiller/requirements.txt --quiet
    echo "  -> Virtual environment ready."
else
    echo "[2/4] Virtual environment already exists."
fi

# ─── 3. Configure Secrets ────────────────────────────────────────────
ENV_FILE="${SCRIPT_DIR}/.env"

if [ -f "$ENV_FILE" ]; then
    echo "[3/4] API keys already configured ($ENV_FILE exists)."
else
    echo "[3/4] Configuring API keys..."
    echo ""
    echo "  ConvergeAI needs credentials to power the Context Distiller."
    echo "  Keys are stored locally in $ENV_FILE (git-ignored)."
    echo "  Press Enter to skip optional fields."
    echo ""

    # --- Required: Anthropic ---
    while true; do
        read -sp "  ANTHROPIC_API_KEY (required): " anthropic_key
        echo ""
        if [ -n "$anthropic_key" ]; then
            break
        fi
        echo "  -> This key is required. Please paste your Anthropic API key."
    done

    # --- Optional: GitHub ---
    read -sp "  GITHUB_TOKEN (optional, for fetching PR context): " github_token
    echo ""

    # --- Optional: Jira ---
    read -p "  JIRA_BASE_URL (optional, e.g. https://yourorg.atlassian.net): " jira_url

    jira_email=""
    jira_token=""
    if [ -n "$jira_url" ]; then
        read -p "  JIRA_EMAIL: " jira_email
        read -sp "  JIRA_API_TOKEN: " jira_token
        echo ""
    fi

    # --- Write the .env file ---
    mkdir -p "$(dirname "$ENV_FILE")"
    cat > "$ENV_FILE" << ENVEOF
# ConvergeAI secrets — generated by setup.sh
# This file is git-ignored. Do not commit.

# Anthropic (required — powers the Context Distiller LLM)
ANTHROPIC_API_KEY="${anthropic_key}"

# GitHub (optional — for fetching PR descriptions)
GITHUB_TOKEN="${github_token}"

# Jira (optional — for fetching internal ticket constraints)
JIRA_BASE_URL="${jira_url}"
JIRA_EMAIL="${jira_email}"
JIRA_API_TOKEN="${jira_token}"

# Distillation model (default: claude-haiku-4-5-20251001)
DISTILL_MODEL=claude-haiku-4-5-20251001
ENVEOF

    chmod 600 "$ENV_FILE"
    echo ""
    echo "  -> Secrets saved to $ENV_FILE"
fi

# ─── 4. Make scripts executable ──────────────────────────────────────
echo "[4/4] Finalizing..."
chmod +x converge.sh 2>/dev/null || true

echo ""
echo "==================================="
echo "  Setup Complete!"
echo "==================================="
echo ""
echo "  Next step — resolve a merge conflict:"
echo ""
echo '  ./converge.sh "There is a merge conflict in main.py.'
echo '  The cherrypick commit sha is <SHA> in repository owner/repo.'
echo '  Please call distill_context and resolve it."'
echo ""
